export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_TO_CART = "REMOVE_TO_CART"
export const EMPTY_CART = "EMPTY_CART"
export const PRODUCT_LIST = "PRODUCT_LIST"
export const PRODUCT_SET = "PRODUCT_SET"
export const PRODUCT_REMOVE="PRODUCT_REMOVE"
export const PRODUCT_EMPTY ="PRODUCT_EMPTY"

export const ADD_WISHLIST ='ADD_WISHLIST'
export const REMOVE_WISHLIST ='REMOVE_WISHLIST'
export const EMPTY_WISHLIST ='EMPTY_WISHLIST'